use_default_settings: true

server:
  secret_key: "75b5c9c660d4809e6bedd0cc1edc8a89da693259fa67be972aad0aa80fd3e7ee"
  bind_address: "0.0.0.0"
  port: 8080
  limiter: false

search:
  safe_search: 0
  autocomplete: "google"
  default_lang: "zh-TW"
  formats:
    - html
    - json

engines:
  - name: google
    engine: google
    shortcut: g
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
  - name: bing
    engine: bing
    shortcut: b
  - name: wikipedia
    engine: wikipedia
    shortcut: wp

outgoing:
  request_timeout: 10.0
  useragent_suffix: ""
